# blocklist
branches:
  except:
  - /.*[.]dmh/
  - /.*[.]wif/

sudo: required
language: c
services:
    - docker

env:
    matrix:
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE USE_CC=gcc   CXXOPTS='-DCMAKE_CPP_FLAGS=-fsigned-char' CURHOST=docker-gcc-x64-signed
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE USE_CC=clang CXXOPTS='-DCMAKE_CPP_FLAGS=-fsigned-char' CURHOST=docker-clang-x64-signed
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE USE_CC=gcc   CXXOPTS='-DCMAKE_CPP_FLAGS=-fsigned-char' CURHOST=docker-gcc-x86-signed
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE USE_CC=clang CXXOPTS='-DCMAKE_CPP_FLAGS=-fsigned-char' CURHOST=docker-clang-x86-signed

        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE USE_CC=gcc   CXXOPTS='-DCMAKE_CPP_FLAGS=-funsigned-char' CURHOST=docker-gcc-x64-unsigned
        - DOCKIMG=unidata/nctests:serial   USECMAKE=TRUE USEAC=TRUE USE_CC=clang CXXOPTS='-DCMAKE_CPP_FLAGS=-funsigned-char' CURHOST=docker-clang-x64-unsigned
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE USE_CC=gcc   CXXOPTS='-DCMAKE_CPP_FLAGS=-funsigned-char' CURHOST=docker-gcc-x86-unsigned
        - DOCKIMG=unidata/nctests:serial32 USECMAKE=TRUE USEAC=TRUE USE_CC=clang CXXOPTS='-DCMAKE_CPP_FLAGS=-funsigned-char' CURHOST=docker-clang-x86-unsigned

before_install:
    - docker pull $DOCKIMG > /dev/null

script:

    - docker run --rm -it -h "$CURHOST" -e USEDASH=FALSE -e RUNC=OFF -e RUNF=OFF -e RUNCXX=TRUE -e RUNP=OFF -e RUNNCO=OFF -e USECMAKE=$USECMAKE -e USEAC=$USEAC -e COPTS=$COPTS -v $(pwd):/netcdf-cxx4 $DOCKIMG
