//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Contacts : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Contacts(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Contacts obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Contacts obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Contacts() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UGridPINVOKE.delete_Contacts(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string name {
    set {
      UGridPINVOKE.Contacts_name_set(swigCPtr, value);
    } 
    get {
      string ret = UGridPINVOKE.Contacts_name_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_int edges {
    set {
      UGridPINVOKE.Contacts_edges_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = UGridPINVOKE.Contacts_edges_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_int contact_type {
    set {
      UGridPINVOKE.Contacts_contact_type_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = UGridPINVOKE.Contacts_contact_type_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public string contact_name_id {
    set {
      UGridPINVOKE.Contacts_contact_name_id_set(swigCPtr, value);
    } 
    get {
      string ret = UGridPINVOKE.Contacts_contact_name_id_get(swigCPtr);
      return ret;
    } 
  }

  public string contact_name_long {
    set {
      UGridPINVOKE.Contacts_contact_name_long_set(swigCPtr, value);
    } 
    get {
      string ret = UGridPINVOKE.Contacts_contact_name_long_get(swigCPtr);
      return ret;
    } 
  }

  public string mesh_from_name {
    set {
      UGridPINVOKE.Contacts_mesh_from_name_set(swigCPtr, value);
    } 
    get {
      string ret = UGridPINVOKE.Contacts_mesh_from_name_get(swigCPtr);
      return ret;
    } 
  }

  public string mesh_to_name {
    set {
      UGridPINVOKE.Contacts_mesh_to_name_set(swigCPtr, value);
    } 
    get {
      string ret = UGridPINVOKE.Contacts_mesh_to_name_get(swigCPtr);
      return ret;
    } 
  }

  public int mesh_from_location {
    set {
      UGridPINVOKE.Contacts_mesh_from_location_set(swigCPtr, value);
    } 
    get {
      int ret = UGridPINVOKE.Contacts_mesh_from_location_get(swigCPtr);
      return ret;
    } 
  }

  public int mesh_to_location {
    set {
      UGridPINVOKE.Contacts_mesh_to_location_set(swigCPtr, value);
    } 
    get {
      int ret = UGridPINVOKE.Contacts_mesh_to_location_get(swigCPtr);
      return ret;
    } 
  }

  public int num_contacts {
    set {
      UGridPINVOKE.Contacts_num_contacts_set(swigCPtr, value);
    } 
    get {
      int ret = UGridPINVOKE.Contacts_num_contacts_get(swigCPtr);
      return ret;
    } 
  }

  public Contacts() : this(UGridPINVOKE.new_Contacts(), true) {
  }

}
