//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class UGridPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="SWIGRegisterExceptionCallbacks_UGrid")]
    public static extern void SWIGRegisterExceptionCallbacks_UGrid(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_UGrid")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_UGrid(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_UGrid(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_UGrid(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="SWIGRegisterStringCallback_UGrid")]
    public static extern void SWIGRegisterStringCallback_UGrid(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_UGrid(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static UGridPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_name_set")]
  public static extern void Contacts_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_name_get")]
  public static extern string Contacts_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_edges_set")]
  public static extern void Contacts_edges_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_edges_get")]
  public static extern global::System.IntPtr Contacts_edges_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_contact_type_set")]
  public static extern void Contacts_contact_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_contact_type_get")]
  public static extern global::System.IntPtr Contacts_contact_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_contact_name_id_set")]
  public static extern void Contacts_contact_name_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_contact_name_id_get")]
  public static extern string Contacts_contact_name_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_contact_name_long_set")]
  public static extern void Contacts_contact_name_long_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_contact_name_long_get")]
  public static extern string Contacts_contact_name_long_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_from_name_set")]
  public static extern void Contacts_mesh_from_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_from_name_get")]
  public static extern string Contacts_mesh_from_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_to_name_set")]
  public static extern void Contacts_mesh_to_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_to_name_get")]
  public static extern string Contacts_mesh_to_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_from_location_set")]
  public static extern void Contacts_mesh_from_location_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_from_location_get")]
  public static extern int Contacts_mesh_from_location_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_to_location_set")]
  public static extern void Contacts_mesh_to_location_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_mesh_to_location_get")]
  public static extern int Contacts_mesh_to_location_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_num_contacts_set")]
  public static extern void Contacts_num_contacts_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Contacts_num_contacts_get")]
  public static extern int Contacts_num_contacts_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_new_Contacts")]
  public static extern global::System.IntPtr new_Contacts();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_delete_Contacts")]
  public static extern void delete_Contacts(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_name_set")]
  public static extern void Mesh1D_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_name_get")]
  public static extern string Mesh1D_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_network_name_set")]
  public static extern void Mesh1D_network_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_network_name_get")]
  public static extern string Mesh1D_network_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_x_set")]
  public static extern void Mesh1D_node_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_x_get")]
  public static extern global::System.IntPtr Mesh1D_node_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_y_set")]
  public static extern void Mesh1D_node_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_y_get")]
  public static extern global::System.IntPtr Mesh1D_node_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_nodes_set")]
  public static extern void Mesh1D_edge_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_nodes_get")]
  public static extern global::System.IntPtr Mesh1D_edge_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_edge_id_set")]
  public static extern void Mesh1D_node_edge_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_edge_id_get")]
  public static extern global::System.IntPtr Mesh1D_node_edge_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_edge_offset_set")]
  public static extern void Mesh1D_node_edge_offset_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_edge_offset_get")]
  public static extern global::System.IntPtr Mesh1D_node_edge_offset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_id_set")]
  public static extern void Mesh1D_node_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_id_get")]
  public static extern string Mesh1D_node_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_long_name_set")]
  public static extern void Mesh1D_node_long_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_node_long_name_get")]
  public static extern string Mesh1D_node_long_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_edge_id_set")]
  public static extern void Mesh1D_edge_edge_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_edge_id_get")]
  public static extern global::System.IntPtr Mesh1D_edge_edge_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_edge_offset_set")]
  public static extern void Mesh1D_edge_edge_offset_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_edge_offset_get")]
  public static extern global::System.IntPtr Mesh1D_edge_edge_offset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_x_set")]
  public static extern void Mesh1D_edge_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_x_get")]
  public static extern global::System.IntPtr Mesh1D_edge_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_y_set")]
  public static extern void Mesh1D_edge_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_edge_y_get")]
  public static extern global::System.IntPtr Mesh1D_edge_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_num_nodes_set")]
  public static extern void Mesh1D_num_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_num_nodes_get")]
  public static extern int Mesh1D_num_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_num_edges_set")]
  public static extern void Mesh1D_num_edges_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_num_edges_get")]
  public static extern int Mesh1D_num_edges_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_is_spherical_set")]
  public static extern void Mesh1D_is_spherical_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_is_spherical_get")]
  public static extern int Mesh1D_is_spherical_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_start_index_set")]
  public static extern void Mesh1D_start_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_start_index_get")]
  public static extern int Mesh1D_start_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_double_fill_value_set")]
  public static extern void Mesh1D_double_fill_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_double_fill_value_get")]
  public static extern double Mesh1D_double_fill_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_int_fill_value_set")]
  public static extern void Mesh1D_int_fill_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh1D_int_fill_value_get")]
  public static extern int Mesh1D_int_fill_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_new_Mesh1D")]
  public static extern global::System.IntPtr new_Mesh1D();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_delete_Mesh1D")]
  public static extern void delete_Mesh1D(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_name_set")]
  public static extern void Mesh2D_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_name_get")]
  public static extern string Mesh2D_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_nodes_set")]
  public static extern void Mesh2D_edge_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_nodes_get")]
  public static extern global::System.IntPtr Mesh2D_edge_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_nodes_set")]
  public static extern void Mesh2D_face_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_nodes_get")]
  public static extern global::System.IntPtr Mesh2D_face_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_node_x_set")]
  public static extern void Mesh2D_node_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_node_x_get")]
  public static extern global::System.IntPtr Mesh2D_node_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_node_y_set")]
  public static extern void Mesh2D_node_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_node_y_get")]
  public static extern global::System.IntPtr Mesh2D_node_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_x_set")]
  public static extern void Mesh2D_edge_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_x_get")]
  public static extern global::System.IntPtr Mesh2D_edge_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_y_set")]
  public static extern void Mesh2D_edge_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_y_get")]
  public static extern global::System.IntPtr Mesh2D_edge_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_x_set")]
  public static extern void Mesh2D_face_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_x_get")]
  public static extern global::System.IntPtr Mesh2D_face_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_y_set")]
  public static extern void Mesh2D_face_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_y_get")]
  public static extern global::System.IntPtr Mesh2D_face_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_faces_set")]
  public static extern void Mesh2D_edge_faces_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_faces_get")]
  public static extern global::System.IntPtr Mesh2D_edge_faces_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_edges_set")]
  public static extern void Mesh2D_face_edges_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_edges_get")]
  public static extern global::System.IntPtr Mesh2D_face_edges_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_faces_set")]
  public static extern void Mesh2D_face_faces_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_faces_get")]
  public static extern global::System.IntPtr Mesh2D_face_faces_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_node_z_set")]
  public static extern void Mesh2D_node_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_node_z_get")]
  public static extern global::System.IntPtr Mesh2D_node_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_z_set")]
  public static extern void Mesh2D_edge_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_edge_z_get")]
  public static extern global::System.IntPtr Mesh2D_edge_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_z_set")]
  public static extern void Mesh2D_face_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_face_z_get")]
  public static extern global::System.IntPtr Mesh2D_face_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_layer_zs_set")]
  public static extern void Mesh2D_layer_zs_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_layer_zs_get")]
  public static extern global::System.IntPtr Mesh2D_layer_zs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_interface_zs_set")]
  public static extern void Mesh2D_interface_zs_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_interface_zs_get")]
  public static extern global::System.IntPtr Mesh2D_interface_zs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_boundary_node_connectivity_set")]
  public static extern void Mesh2D_boundary_node_connectivity_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_boundary_node_connectivity_get")]
  public static extern global::System.IntPtr Mesh2D_boundary_node_connectivity_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_volume_coordinates_set")]
  public static extern void Mesh2D_volume_coordinates_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_volume_coordinates_get")]
  public static extern global::System.IntPtr Mesh2D_volume_coordinates_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_nodes_set")]
  public static extern void Mesh2D_num_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_nodes_get")]
  public static extern int Mesh2D_num_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_edges_set")]
  public static extern void Mesh2D_num_edges_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_edges_get")]
  public static extern int Mesh2D_num_edges_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_faces_set")]
  public static extern void Mesh2D_num_faces_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_faces_get")]
  public static extern int Mesh2D_num_faces_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_layers_set")]
  public static extern void Mesh2D_num_layers_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_layers_get")]
  public static extern int Mesh2D_num_layers_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_start_index_set")]
  public static extern void Mesh2D_start_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_start_index_get")]
  public static extern int Mesh2D_start_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_face_nodes_max_set")]
  public static extern void Mesh2D_num_face_nodes_max_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_num_face_nodes_max_get")]
  public static extern int Mesh2D_num_face_nodes_max_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_is_spherical_set")]
  public static extern void Mesh2D_is_spherical_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_is_spherical_get")]
  public static extern int Mesh2D_is_spherical_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_double_fill_value_set")]
  public static extern void Mesh2D_double_fill_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_double_fill_value_get")]
  public static extern double Mesh2D_double_fill_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_int_fill_value_set")]
  public static extern void Mesh2D_int_fill_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Mesh2D_int_fill_value_get")]
  public static extern int Mesh2D_int_fill_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_new_Mesh2D")]
  public static extern global::System.IntPtr new_Mesh2D();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_delete_Mesh2D")]
  public static extern void delete_Mesh2D(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_name_set")]
  public static extern void Network1D_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_name_get")]
  public static extern string Network1D_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_x_set")]
  public static extern void Network1D_node_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_x_get")]
  public static extern global::System.IntPtr Network1D_node_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_y_set")]
  public static extern void Network1D_node_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_y_get")]
  public static extern global::System.IntPtr Network1D_node_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_id_set")]
  public static extern void Network1D_node_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_id_get")]
  public static extern string Network1D_node_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_long_name_set")]
  public static extern void Network1D_node_long_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_node_long_name_get")]
  public static extern string Network1D_node_long_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_nodes_set")]
  public static extern void Network1D_edge_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_nodes_get")]
  public static extern global::System.IntPtr Network1D_edge_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_length_set")]
  public static extern void Network1D_edge_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_length_get")]
  public static extern global::System.IntPtr Network1D_edge_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_order_set")]
  public static extern void Network1D_edge_order_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_order_get")]
  public static extern global::System.IntPtr Network1D_edge_order_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_id_set")]
  public static extern void Network1D_edge_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_id_get")]
  public static extern string Network1D_edge_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_long_name_set")]
  public static extern void Network1D_edge_long_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_edge_long_name_get")]
  public static extern string Network1D_edge_long_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_geometry_nodes_x_set")]
  public static extern void Network1D_geometry_nodes_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_geometry_nodes_x_get")]
  public static extern global::System.IntPtr Network1D_geometry_nodes_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_geometry_nodes_y_set")]
  public static extern void Network1D_geometry_nodes_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_geometry_nodes_y_get")]
  public static extern global::System.IntPtr Network1D_geometry_nodes_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_edge_geometry_nodes_set")]
  public static extern void Network1D_num_edge_geometry_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_edge_geometry_nodes_get")]
  public static extern global::System.IntPtr Network1D_num_edge_geometry_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_geometry_nodes_set")]
  public static extern void Network1D_num_geometry_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_geometry_nodes_get")]
  public static extern int Network1D_num_geometry_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_nodes_set")]
  public static extern void Network1D_num_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_nodes_get")]
  public static extern int Network1D_num_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_edges_set")]
  public static extern void Network1D_num_edges_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_num_edges_get")]
  public static extern int Network1D_num_edges_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_is_spherical_set")]
  public static extern void Network1D_is_spherical_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_is_spherical_get")]
  public static extern int Network1D_is_spherical_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_start_index_set")]
  public static extern void Network1D_start_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_Network1D_start_index_get")]
  public static extern int Network1D_start_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_new_Network1D")]
  public static extern global::System.IntPtr new_Network1D();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_delete_Network1D")]
  public static extern void delete_Network1D(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_new_UGridState__SWIG_0")]
  public static extern global::System.IntPtr new_UGridState__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_new_UGridState__SWIG_1")]
  public static extern global::System.IntPtr new_UGridState__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_ncFile_set")]
  public static extern void UGridState_m_ncFile_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_ncFile_get")]
  public static extern global::System.IntPtr UGridState_m_ncFile_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_mesh1d_set")]
  public static extern void UGridState_m_mesh1d_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_mesh1d_get")]
  public static extern global::System.IntPtr UGridState_m_mesh1d_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_network1d_set")]
  public static extern void UGridState_m_network1d_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_network1d_get")]
  public static extern global::System.IntPtr UGridState_m_network1d_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_mesh2d_set")]
  public static extern void UGridState_m_mesh2d_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_mesh2d_get")]
  public static extern global::System.IntPtr UGridState_m_mesh2d_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_contacts_set")]
  public static extern void UGridState_m_contacts_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_m_contacts_get")]
  public static extern global::System.IntPtr UGridState_m_contacts_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_set_dimension")]
  public static extern void UGridState_set_dimension(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_UGridState_get_dimension")]
  public static extern global::System.IntPtr UGridState_get_dimension(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_delete_UGridState")]
  public static extern void delete_UGridState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_locations_attribute_names_set")]
  public static extern void locations_attribute_names_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_locations_attribute_names_get")]
  public static extern global::System.IntPtr locations_attribute_names_get();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_locations_ugrid_dimensions_set")]
  public static extern void locations_ugrid_dimensions_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_locations_ugrid_dimensions_get")]
  public static extern global::System.IntPtr locations_ugrid_dimensions_get();

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_error_get")]
  public static extern int ug_error_get(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_name_get_length")]
  public static extern int ug_name_get_length(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_name_get_long_length")]
  public static extern int ug_name_get_long_length(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_entity_get_node_location_enum")]
  public static extern int ug_entity_get_node_location_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_entity_get_edge_location_enum")]
  public static extern int ug_entity_get_edge_location_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_entity_get_face_location_enum")]
  public static extern int ug_entity_get_face_location_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_get_network1d_enum")]
  public static extern int ug_topology_get_network1d_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_get_mesh1d_enum")]
  public static extern int ug_topology_get_mesh1d_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_get_mesh2d_enum")]
  public static extern int ug_topology_get_mesh2d_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_get_contacts_enum")]
  public static extern int ug_topology_get_contacts_enum(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_get_count")]
  public static extern int ug_topology_get_count(int jarg1, int jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_count_data_variables")]
  public static extern int ug_topology_count_data_variables(int jarg1, int jarg2, int jarg3, int jarg4, ref int jarg5);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_get_data_variables_names")]
  public static extern int ug_topology_get_data_variables_names(int jarg1, int jarg2, int jarg3, int jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_topology_define_double_variable_on_location")]
  public static extern int ug_topology_define_double_variable_on_location(int jarg1, int jarg2, int jarg3, int jarg4, string jarg5, string jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_count_attributes")]
  public static extern int ug_variable_count_attributes(int jarg1, string jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_get_attributes_values")]
  public static extern int ug_variable_get_attributes_values(int jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_get_attributes_names")]
  public static extern int ug_variable_get_attributes_names(int jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_count_dimensions")]
  public static extern int ug_variable_count_dimensions(int jarg1, string jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_get_data_dimensions")]
  public static extern int ug_variable_get_data_dimensions(int jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_get_data_double")]
  public static extern int ug_variable_get_data_double(int jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_get_data_int")]
  public static extern int ug_variable_get_data_int(int jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_get_data_char")]
  public static extern int ug_variable_get_data_char(int jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_file_read_mode")]
  public static extern int ug_file_read_mode(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_file_write_mode")]
  public static extern int ug_file_write_mode(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_file_replace_mode")]
  public static extern int ug_file_replace_mode(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_file_open")]
  public static extern int ug_file_open(string jarg1, int jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_file_close")]
  public static extern int ug_file_close(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_network1d_def")]
  public static extern int ug_network1d_def(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_network1d_put")]
  public static extern int ug_network1d_put(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_network1d_inq")]
  public static extern int ug_network1d_inq(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_network1d_get")]
  public static extern int ug_network1d_get(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh1d_def")]
  public static extern int ug_mesh1d_def(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh1d_put")]
  public static extern int ug_mesh1d_put(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh1d_inq")]
  public static extern int ug_mesh1d_inq(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh1d_get")]
  public static extern int ug_mesh1d_get(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh2d_def")]
  public static extern int ug_mesh2d_def(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh2d_put")]
  public static extern int ug_mesh2d_put(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh2d_inq")]
  public static extern int ug_mesh2d_inq(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_mesh2d_get")]
  public static extern int ug_mesh2d_get(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_contacts_def")]
  public static extern int ug_contacts_def(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref int jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_contacts_put")]
  public static extern int ug_contacts_put(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_contacts_inq")]
  public static extern int ug_contacts_inq(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_contacts_get")]
  public static extern int ug_contacts_get(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_variable_int_define")]
  public static extern int ug_variable_int_define(int jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_attribute_int_define")]
  public static extern int ug_attribute_int_define(int jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_attribute_char_define")]
  public static extern int ug_attribute_char_define(int jarg1, string jarg2, string jarg3, string jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_attribute_double_define")]
  public static extern int ug_attribute_double_define(int jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_attribute_global_char_define")]
  public static extern int ug_attribute_global_char_define(int jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_get_edges_location_type")]
  public static extern int ug_get_edges_location_type(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_get_nodes_location_type")]
  public static extern int ug_get_nodes_location_type(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_get_faces_location_type")]
  public static extern int ug_get_faces_location_type(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_get_int_fill_value")]
  public static extern int ug_get_int_fill_value(ref int jarg1);

  [global::System.Runtime.InteropServices.DllImport("UGridNET", EntryPoint="CSharp_ug_get_double_fill_value")]
  public static extern int ug_get_double_fill_value(ref double jarg1);
}
