# version
set(UGRID_PROJECT_VERSION_MAJOR 0)
set(UGRID_PROJECT_VERSION_MINOR 1)
set(UGRID_PROJECT_VERSION_PATCH 0)
if(DEFINED ENV{UGRID_BUILD_NUMBER})
  set(UGRID_PROJECT_VERSION_TWEAK $ENV{UGRID_BUILD_NUMBER})
else()
  set(UGRID_PROJECT_VERSION_TWEAK 0)
endif()
set(
  GLOB_UGRID_PROJECT_VERSION 
  "${UGRID_PROJECT_VERSION_MAJOR}.${UGRID_PROJECT_VERSION_MINOR}.${UGRID_PROJECT_VERSION_PATCH}.${UGRID_PROJECT_VERSION_TWEAK}"
  CACHE STRING "Project version"
)

# year
string(TIMESTAMP GLOB_CURRENT_YEAR "%Y")
set(GLOB_CURRENT_YEAR ${GLOB_CURRENT_YEAR} CACHE STRING "Current year")
