# version
set(UGRID_PROJECT_VERSION_MAJOR 0)
set(UGRID_PROJECT_VERSION_MINOR 0)
set(UGRID_PROJECT_VERSION_PATCH 0)
if(DEFINED ENV{UGRID_BUILD_NUMBER})
  set(UGRID_PROJECT_VERSION_TWEAK $ENV{UGRID_BUILD_NUMBER})
else()
  set(UGRID_PROJECT_VERSION_TWEAK 0)
endif()
set(
  GLOB_UGRID_PROJECT_VERSION 
  "${UGRID_PROJECT_VERSION_MAJOR}.${UGRID_PROJECT_VERSION_MINOR}.${UGRID_PROJECT_VERSION_PATCH}.${UGRID_PROJECT_VERSION_TWEAK}"
  CACHE STRING "Project version"
)

# year
string(TIMESTAMP GLOB_CURRENT_YEAR "%Y")
set(GLOB_CURRENT_YEAR ${GLOB_CURRENT_YEAR} CACHE STRING "Current year")

# .NET config
if(BUILD_DOTNET_WRAPPER)
  # .NET SDK
  set(GLOB_DOTNET_SDK "Microsoft.NET.Sdk" CACHE STRING ".NET SDK")
  # List of .NET target frameworks (semicolon-delimited)
  set(GLOB_LIB_DOTNET_TARGET_FRAMEWORKS "netstandard2.0;" CACHE STRING "Library .NET target framework" FORCE)
  set(GLOB_TEST_DOTNET_TARGET_FRAMEWORKS "net481;" CACHE STRING "Test .NET target framework" FORCE)
  # .NET language version
  set(GLOB_CSHARP_LANGUAGE_VERSION "7.3" CACHE STRING "C# Compiler Options for language feature rules") 
endif()
