name: Deploy documentation

on:
  push:
    branches: [main]

jobs:
  check:
    name: DoxygenDeploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install doxygen
        run: sudo apt-get install doxygen

      - name: Run doxygen
        run: python3 scripts/doxygen_ci.py

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/html
