name: Check documentation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: DoxygenCheck

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install doxygen
        run: sudo apt-get install doxygen

      - name: Check doxygen
        run: |
          # Set error mode. Makes bash bail on first non-zero exit code
          set -e 
          python3 scripts/doxygen_ci.py --fail-with-warnings
